app_root: .
binary_name: {{cookiecutter.app_name}}
build_delay: 200ns
build_flags: []
build_path: /tmp/{{cookiecutter.app_name}}
build_target_path: ""
command_env: []
command_flags: ["--conf=./config.toml", "server"]
enable_colors: true
ignored_folders:
  - vendor
  - log
  - logs
  - tmp
  - node_modules
  - bin
  - templates
included_extensions:
  - .go
log_name: ""
