app_root: .
binary_name: refresh-build
build_delay: 200ns
build_flags: []
build_path: /var/folders/7f/zh3ncx6x2vgcf3d08p08j9jc0000gn/T/
build_target_path: ""
command_env: []
command_flags: ["--conf=./config.toml", "server"]
enable_colors: true
ignored_folders:
  - vendor
  - log
  - logs
  - tmp
  - node_modules
  - bin
  - templates
included_extensions:
  - .go
log_name: ""
