[Server]
Env = "Dev"
Listen = ":42424"
MaxHttpRequestBody = 4
TLSKey = ""
TLSPem = ""
UseTLS = false

[Database]
{% if cookiecutter.use_db == "postgres" -%}host=127.0.0.1 user=root dbname=tom sslmode=disable password=password port=5432{%- endif %}{% if cookiecutter.use_db == "mysql" -%}root:password@127.0.0.1:3306/dbname?charset=utf8&parseTime=True&loc=Local{%- endif %}{% if cookiecutter.use_db == "sqlite" -%}./sqlite.db{%- endif %}

DSN = "host=127.0.0.1 user=root dbname={{cookiecutter.app_name}} sslmode=disable password=password port=5432"
[Permission]
DB = "permission"
DSN = "host=127.0.0.1 user=root dbname={{cookiecutter.app_name}}-permission sslmode=disable password=password port=5432"
