[Server]
Env = "Dev"
Listen = ":42424"
MaxHttpRequestBody = 4
TLSKey = ""
TLSPem = ""
UseTLS = false

[Database]
DSN = "host=127.0.0.1 user=root dbname={{cookiecutter.app_name}} sslmode=disable password=password port=5432"
[Permission]
DB = "permission"
DSN = "host=127.0.0.1 user=root dbname={{cookiecutter.app_name}}-permission sslmode=disable password=password port=5432"
